"""initial_schema

Revision ID: 85cc9d75cbbc
Revises: 
Create Date: 2026-07-27 15:44:10.414220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85cc9d75cbbc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_insights_user_id'), table_name='ai_insights')
    op.drop_index(op.f('idx_health_user_id'), table_name='financial_health_scores')
    op.drop_index(op.f('idx_goals_user_id'), table_name='goals')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('idx_transactions_user_category'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_user_date'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_user_type'), table_name='transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_transactions_user_type'), 'transactions', ['user_id', 'transaction_type'], unique=False)
    op.create_index(op.f('idx_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index(op.f('idx_transactions_user_date'), 'transactions', ['user_id', 'date'], unique=False)
    op.create_index(op.f('idx_transactions_user_category'), 'transactions', ['user_id', 'category'], unique=False)
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_index(op.f('idx_health_user_id'), 'financial_health_scores', ['user_id'], unique=False)
    op.create_index(op.f('idx_insights_user_id'), 'ai_insights', ['user_id'], unique=False)
    # ### end Alembic commands ###
